// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FirstMachineLearningML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public float Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public float Col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public float Col2 { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public float Col3 { get; set; }


        [ColumnName("col4"), LoadColumn(4)]
        public float Col4 { get; set; }


        [ColumnName("col5"), LoadColumn(5)]
        public float Col5 { get; set; }


        [ColumnName("col6"), LoadColumn(6)]
        public float Col6 { get; set; }


        [ColumnName("col7"), LoadColumn(7)]
        public float Col7 { get; set; }


        [ColumnName("col8"), LoadColumn(8)]
        public string Col8 { get; set; }


    }
}
