// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FirstMachineLearningML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public float col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public float col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public float col2 { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public float col3 { get; set; }


        [ColumnName("col4"), LoadColumn(4)]
        public float col4 { get; set; }


        [ColumnName("col5"), LoadColumn(5)]
        public float col5 { get; set; }


        [ColumnName("col6"), LoadColumn(6)]
        public float col6 { get; set; }


        [ColumnName("col7"), LoadColumn(7)]
        public float col7 { get; set; }


        [ColumnName("col8"), LoadColumn(8)]
        public string col8 { get; set; }


    }
}
